#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 102130416804-3spopldc6domf1v6hr4rrkhes6audkun.apps.googleusercontent.com
#            client-secret: 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
#  mvc.hiddenmethod.filter.enabled: true
#  thymeleaf:
#    cache: false
#    #  check-template: true
#    #  check-template-location: true
#    #  content-type: text/html
#    #  enabled: true
#    #  encoding: UTF-8
#    #  mode: HTML5
#    prefix: classpath:/templates/
#    #  suffix: .html
##  liquibase:
##    enabled: true
###    url: jdbc:postgresql://${dbhost}:${dbport}/${dbname}
##    user: ${dbuser}
##    password: ${dbpass}
##    change-log: db/changelog/db.changelog-master.yaml
#
#  liquibase:
#    enabled: true
#    url: jdbc:postgresql://localhost:5432/project3
#    user: postgres
#    password: root
#    change-log: db/changelog/db.changelog-master.yaml
#  jpa:
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: false #//
#    hibernate:
#      ddl-auto: none
#      open-in-view: false
#    properties:
#      hibernate:
#        metadata_builder_contributor: com.java.project3.configuration.SqlFunctionsMetadataBuilderContributor
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${dbhost}:${dbport}/${dbname}
#    username: ${dbuser}
#    password: ${dbpass}
#    hikari:
#      connection-timeout: 20000
#      minimum-idle: 1
#      maximum-pool-size: 2
#      idleTimeout: 10000
#      maxLifetime: 30000
#  servlet:
#    multipart:
#      max-file-size: 30MB
#      max-request-size: 30MB
#      enabled: true
#  messages:
#    basename: i18n/messages
#server:
#  port: 8080
#  tomcat:
#    max-swallow-size: -1
#external:
#  port: 8080
#file:
#  upload_dir: ${upload_dir}
#service:
#  notification:
#    url: ${notify_url}
#  job:
#    url: ${job_url}